### ISSUE TITLE
AttributeError: 'HTTPError' object has no attribute 'headers'

### ISSUE THREAD

**Issue by guandalf** [z4r/python-rtkit#7]
(kanbanizesync)guandalf@earth:~/Workspace/kanbanizesync/src$ python kize2rt.py 
[DEBUG] POST search/ticket?orderby=%2Bid&query=%28Status+%3D+%27open%27+OR+Status+%3D+%27new%27+OR+Status+%3D+%27stalled%27%29+AND+%28Queue+%3D+%27qaupdate%27%29&format=s
[DEBUG] {'Accept': 'text/plain'}
[DEBUG] None
Traceback (most recent call last):
  File "kize2rt.py", line 35, in <module>
    rt_all_tickets = rt.post(path='search/ticket?%s' % params)
  File "/home/guandalf/Virtualenv/kanbanizesync/local/lib/python2.7/site-packages/rtkit/resource.py", line 20, in post
    return self.request('POST', path, payload, headers)
  File "/home/guandalf/Virtualenv/kanbanizesync/local/lib/python2.7/site-packages/rtkit/resource.py", line 39, in request
    return self.response_cls(req, response)
  File "/home/guandalf/Virtualenv/kanbanizesync/local/lib/python2.7/site-packages/rtkit/resource.py", line 48, in **init**
    self.headers    = response.headers
AttributeError: 'HTTPError' object has no attribute 'headers'

Betrayed by urllib2? Try "requests" :)

**Comment by morallo** [comment]
@guandalf were you able to fix this bug? I have exactly the same error.

**Comment by guandalf** [comment]
@morallo I haven't worked on it anymore. Sorry.
